[package]
name = "ferrum-native-fuzz"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ferrum-native = { path = ".." }

[[bin]]
name = "nbt_parse"
path = "fuzz_targets/nbt_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lz4_decode"
path = "fuzz_targets/lz4_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "palette_unpack"
path = "fuzz_targets/palette_unpack.rs"
test = false
doc = false
bench = false

[[bin]]
name = "palette_pack"
path = "fuzz_targets/palette_pack.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
