use std::fs;
use std::path::PathBuf;

use ferrum::abi::FERRUM_OK;
use ferrum::codec::decode_stream;

/// Verifies the Java-authored lz4-java block-stream corpus.
///
/// The corpus lives under `tests/golden/lz4/` and is generated by
/// `:modules:ferrum-codec:generateLz4Golden`. If it is absent the test is a no-op so a fresh
/// checkout still builds.
#[test]
fn java_golden_corpus_decodes() {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/lz4");
    if !directory.is_dir() {
        eprintln!("LZ4 golden corpus not present; skipping");
        return;
    }

    let mut checked = 0;
    for entry in fs::read_dir(&directory).expect("read golden dir") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|value| value.to_str()) != Some("lz4") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("file stem");
        let expected = fs::read(directory.join(format!("{stem}.raw"))).expect("raw");
        let stream = fs::read(&path).expect("lz4");

        let mut out = vec![0u8; expected.len()];
        let mut written = 0usize;
        assert_eq!(
            decode_stream(&stream, &mut out, &mut written),
            FERRUM_OK,
            "decode {stem}"
        );
        assert_eq!(written, expected.len(), "length {stem}");
        assert_eq!(out, expected, "content {stem}");

        checked += 1;
    }

    assert!(checked > 0, "golden corpus was empty");
}
