use std::fs;
use std::path::PathBuf;

use ferrum::nbt::mutf8;

/// Verifies the Java-authored MUTF-8 golden corpus (ADR-0002).
///
/// The corpus lives under `tests/golden/nbt/` and is generated by
/// `:modules:ferrum-nbt:generateNbtGolden`. If it is absent the test is a no-op so a fresh checkout
/// still builds.
#[test]
fn java_golden_corpus_round_trips() {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/nbt");
    if !directory.is_dir() {
        eprintln!("NBT golden corpus not present; skipping");
        return;
    }

    let mut checked = 0;
    for entry in fs::read_dir(&directory).expect("read golden dir") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|value| value.to_str()) != Some("bin") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("file stem")
            .to_string();

        let bytes = fs::read(&path).expect("read bin");
        let declared = u16::from_be_bytes([bytes[0], bytes[1]]) as usize;
        let body = &bytes[2..];
        assert_eq!(declared, body.len(), "length prefix mismatch for {name}");

        let units = mutf8::decode(body).expect("decode");
        let expected_bytes = fs::read(directory.join(format!("{name}.utf16le"))).expect("utf16le");
        let expected: Vec<u16> = expected_bytes
            .as_chunks::<2>()
            .0
            .iter()
            .map(|pair| u16::from_le_bytes(*pair))
            .collect();
        assert_eq!(units, expected, "decode mismatch for {name}");

        let mut encoded = vec![0u8; body.len()];
        let written = mutf8::encode(&units, &mut encoded).expect("encode");
        assert_eq!(&encoded[..written], body, "encode mismatch for {name}");

        checked += 1;
    }

    assert!(checked > 0, "golden corpus was empty");
}
