//! Verifies the Java-authored noise descriptor corpus byte for byte (ADR-0017).
//!
//! The corpus lives under `tests/golden/noise/` and is generated by
//! `:modules:ferrum-noise:generateNoiseGolden`. It is absent on a fresh checkout, so the test is a
//! no-op there.

use std::fs;
use std::path::PathBuf;

use ferrum::noise::{ferrum_noise_batch, ferrum_noise_create, ferrum_noise_destroy};

#[test]
fn java_golden_corpus_matches_raw_bits() {
    let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/noise");
    if !directory.is_dir() {
        eprintln!("noise golden corpus not present; skipping");
        return;
    }

    let mut checked = 0;
    for entry in fs::read_dir(&directory).expect("read noise golden dir") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|value| value.to_str()) != Some("desc") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("file stem")
            .to_string();

        let descriptor = fs::read(&path).expect("read descriptor");
        let coord_bytes = fs::read(directory.join(format!("{name}.coords"))).expect("read coords");
        let expected_bytes =
            fs::read(directory.join(format!("{name}.expected"))).expect("read expected");

        let coordinates: Vec<f64> = coord_bytes
            .as_chunks::<8>()
            .0
            .iter()
            .map(|chunk| f64::from_le_bytes(*chunk))
            .collect();
        let expected: Vec<u64> = expected_bytes
            .as_chunks::<8>()
            .0
            .iter()
            .map(|chunk| u64::from_le_bytes(*chunk))
            .collect();
        let samples = expected.len();
        assert_eq!(
            coordinates.len(),
            samples * 3,
            "coordinate/expected length mismatch for {name}"
        );

        let xs: Vec<f64> = (0..samples).map(|index| coordinates[index * 3]).collect();
        let ys: Vec<f64> = (0..samples)
            .map(|index| coordinates[index * 3 + 1])
            .collect();
        let zs: Vec<f64> = (0..samples)
            .map(|index| coordinates[index * 3 + 2])
            .collect();
        let mut actual = vec![0f64; samples];

        let mut handle = 0u64;
        // SAFETY: `descriptor` is a valid slice and `handle` is valid for one write.
        let status =
            unsafe { ferrum_noise_create(descriptor.as_ptr(), descriptor.len(), &mut handle) };
        assert_eq!(status, 0, "create failed for {name}");

        // SAFETY: all pointers are valid for `samples` elements.
        let status = unsafe {
            ferrum_noise_batch(
                handle,
                xs.as_ptr(),
                ys.as_ptr(),
                zs.as_ptr(),
                actual.as_mut_ptr(),
                samples,
                0,
            )
        };
        assert_eq!(status, 0, "batch failed for {name}");

        for index in 0..samples {
            assert_eq!(
                actual[index].to_bits(),
                expected[index],
                "raw-bits mismatch for {name} at sample {index}: got {}, expected {}",
                actual[index],
                f64::from_bits(expected[index])
            );
        }

        let _ = ferrum_noise_destroy(handle);
        checked += 1;
    }

    assert!(checked > 0, "noise golden corpus was empty");
}
